### ISSUE TITLE
TypeError: Fetch argument 0 has invalid type <class 'numpy.int64'>, must be a string or Tensor. (Can not convert a int64 into a Tensor or Operation.)

### ISSUE THREAD

**Issue by BlcDec** [dnguyengithub/MultitaskAIS#14]
Hello, I run the python3  multitaskAIS.py --mode=train --logdir=./chkpt --bound=elbo --summarize_every=100 --latent_size=100 --batch_size=50 --num_samples=16 --learning_rate=0.0003 with the following problem 
```Traceback (most recent call last):
  File "...tensorflowpy36\lib\site-packages\tensorflow\python\client\session.py", line 300, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "...tensorflowpy36\lib\site-packages\tensorflow\python\framework\ops.py", line 3475, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "...tensorflowpy36\lib\site-packages\tensorflow\python\framework\ops.py", line 3567, in _as_graph_element_locked
    types_str))
TypeError: Can not convert a int64 into a Tensor or Operation.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/project/MultitaskAIS/python3/MultitaskAIS/multitaskAIS.py", line 55, in <module>
    runners.run_train(config)
  File "D:\project\MultitaskAIS\python3\MultitaskAIS\runners.py", line 327, in run_train
    log_step_count_steps=config.summarize_every) as sess:
  File "...tensorflowpy36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 508, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "...tensorflowpy36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 934, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "...tensorflowpy36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 648, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "...\tensorflowpy36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1122, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "...\tensorflowpy36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1127, in _create_session
    return self._sess_creator.create_session()
  File "...\tensorflowpy36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 812, in create_session
    hook.after_create_session(self.tf_sess, self.coord)
  File "C...\tensorflowpy36\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 568, in after_create_session
    self._save(session, global_step)
  File "...\tensorflowpy36\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py", line 599, in _save
    self._get_saver().save(session, self._save_path, global_step=step)
  File "...\tensorflowpy36\lib\site-packages\tensorflow\python\training\saver.py", line 1143, in save
    global_step = training_util.global_step(sess, global_step)
  File ...\tensorflowpy36\lib\site-packages\tensorflow\python\training\training_util.py", line 69, in global_step
    return int(sess.run(global_step_tensor))
  File "...\tensorflowpy36\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "...s\tensorflowpy36\lib\site-packages\tensorflow\python\client\session.py", line 1137, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "...\tensorflowpy36\lib\site-packages\tensorflow\python\client\session.py", line 471, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "...tensorflowpy36\lib\site-packages\tensorflow\python\client\session.py", line 271, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File ...\tensorflowpy36\lib\site-packages\tensorflow\python\client\session.py", line 304, in __init__
    (fetch, type(fetch), str(e)))
TypeError: Fetch argument 0 has invalid type <class 'numpy.int64'>, must be a string or Tensor. (Can not convert a int64 into a Tensor or Operation.)
```

 , my environment is python3.6,tensorflow 1.13.1 is samilar with requirments.txt.

Look forward your reply.

**Comment by duonginspace** [comment]
Hi, 
Which branch did you clone the code from? 
I can't reproduce your error on branch Master (my code).
The code in branch Python3 is written by @JSchuurmans , I haven't checked it yet.
@JSchuurmans : could you take a look? Thank you.

**Comment by duonginspace** [comment]
Hi, 
I've just updated the `master` branch to python3. 
It works for me.
You can update your repository, clone the PYTHON3GPU environment (using `requirements.yml`) to run the code.
